export default {
    SEARCH_INPUT_FOCUS: 'header/SEARCH_INPUT_FOCUS',
    SEARCH_INPUT_BLUR: 'header/SEARCH_INPUT_BLUR',
    SEARCH_INFO_LIST: 'header/SEARCH_INFO_LIST',
    MOUSE_ENTER: 'header/MOUSE_ENTER',
    MOUSE_LEAVE: 'header/MOUSE_LEAVE',
} 